# Generated by Django 5.1.6 on 2025-02-05 20:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='type',
            field=models.CharField(choices=[('Acquisition', 'Acquisition'), ('Condo Inventory', 'Condo Inventory'), ('Construction', 'Construction'), ('Covered Land', 'Covered Land'), ('Office to Condo Conversion', 'Office to Condo Conversion'), ('Office to Multifamily Conversion', 'Office to Multifamily Conversion'), ('Refinance', 'Refinance'), ('TCO', 'TCO')], default='Acquisition', max_length=100),
        ),
    ]
