# Generated by Django 5.1.6 on 2025-02-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_deal_date_deal_time_deal_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='deal',
            old_name='type',
            new_name='deal_type',
        ),
        migrations.AddField(
            model_name='deal',
            name='address',
            field=models.CharField(default='Your default address', max_length=200),
        ),
        migrations.AddField(
            model_name='deal',
            name='asset_class',
            field=models.CharField(choices=[('Hospitality', 'Hospitality'), ('Industrial', 'Industrial'), ('Land', 'Land'), ('Mixed-Use', 'Mixed-Use'), ('Multifamily', 'Multifamily'), ('Office', 'Office'), ('Retail', 'Retail')], default='Hospitality', max_length=100),
        ),
        migrations.AddField(
            model_name='deal',
            name='description',
            field=models.TextField(default='default description'),
        ),
        migrations.AddField(
            model_name='deal',
            name='image_url',
            field=models.URLField(default='default url'),
        ),
        migrations.AddField(
            model_name='deal',
            name='maximum_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='minimum_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='rate_type',
            field=models.CharField(choices=[('Fixed', 'Fixed'), ('Floating Rate (1-YR Treasury)', 'Floating Rate (1-YR Treasury)'), ('Floating Rate (10-YR Treasury)', 'Floating Rate (10-YR Treasury)'), ('Floating Rate (5-YR Treasury)', 'Floating Rate (5-YR Treasury)'), ('Floating Rate (LIBOR)', 'Floating Rate (LIBOR)'), ('Floating Rate (SOFR)', 'Floating Rate (SOFR)'), ('Other', 'Other')], default='Fixed', max_length=100),
        ),
        migrations.AddField(
            model_name='deal',
            name='square_feet',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='deal',
            name='stories',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='deal',
            name='developer',
            field=models.ManyToManyField(to='main_app.developer'),
        ),
    ]
