# Generated by Django 5.1.6 on 2025-02-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_developer_rename_type_deal_deal_type_deal_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='asset_class',
            field=models.CharField(choices=[('Condo', 'Condo'), ('Hospitality', 'Hospitality'), ('Industrial', 'Industrial'), ('Land', 'Land'), ('Mixed-Use', 'Mixed-Use'), ('Multifamily', 'Multifamily'), ('Office', 'Office'), ('Retail', 'Retail')], default='Condo', max_length=100),
        ),
    ]
