# Generated by Django 5.1.6 on 2025-03-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_deal_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
