# Generated by Django 5.1.6 on 2025-03-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_deal_date_alter_deal_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='image_url',
            field=models.CharField(default='default url'),
        ),
    ]
