# Generated by Django 5.1.6 on 2025-03-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_deal_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='time',
        ),
        migrations.AlterField(
            model_name='deal',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
