# Generated by Django 5.1.6 on 2025-03-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_deal_time_alter_deal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
