# Generated by Django 5.1.6 on 2025-03-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_deal_latitude_deal_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='units',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
