# Generated by Django 5.1.6 on 2025-03-20 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_deal_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='image_url',
            field=models.CharField(default='default url'),
        ),
    ]
